### ISSUE TITLE
Send game history to the live view at the live view register event

### ISSUE THREAD

**Issue by locram** [Zuehlke/HouseOfCards#32]
When the game is already in progress and a new viewer joins, she must know the current state to display the game in an useful way. Add functionality to send the current state to the live view at the register event.

**Comment by leozulfiu** [comment]
Maybe we can create a "LiveviewHistoryService" which holds the current history of the game.

Possible problems:

* synchronous and asynchronous communication because on one side you have the GameViewerController which wants to get the current history and on the other the GameViewerPublishService which should call the service for storing the events.
* maybe dependency injection will not work because spring :broken_heart: akka.
